# Generated by Django 4.0 on 2022-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_task_finish_remove_task_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
